name: 'Create README.md file'
on:
  push:
    branches:
      - master
jobs:
  readme:
    name: 'readme-create'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'Set up Python 3.7'
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: 'create readme'
        uses: 'clouddrove/github-actions@9.0.3'
        with:
          actions_subcommand: 'readme'
          github_token: '${{ secrets.GITHUB }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'pre-commit check errors'
        uses: pre-commit/action@v3.0.1
        continue-on-error: true

      - name: 'pre-commit fix erros'
        uses: pre-commit/action@v3.0.1
        continue-on-error: true

      - name: 'push readme'
        uses: 'clouddrove/github-actions@9.0.3'
        continue-on-error: true
        with:
          actions_subcommand: 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Slack Notification'
        uses: clouddrove/action-slack@v2
        with:
          status: ${{ job.status }}
          fields: repo,author
          author_name: 'CloudDrove'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_TERRAFORM }} # required
        if: always()

 # Create README for each Submodules
  readme-create-modules:
    name: 'modules readme-create'
    runs-on: ubuntu-latest
    steps:
      - name: Updating GitHub Token
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB }}
        run: echo "GH_TOKEN=${GITHUB_TOKEN}" >> $GITHUB_ENV

      - name: checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          token: ${{ env.GH_TOKEN }}

      - name: Generate TF Docs
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: modules/aws_github_oidc_role
          git-push: true
          template: |-
            <!-- BEGINNING OF PRE-COMMIT-TERRAFORM DOCS HOOK -->
            {{ .Content }}
            <!-- END OF PRE-COMMIT-TERRAFORM DOCS HOOK -->
          git-push-user-name: "clouddrove-ci"
          git-push-user-email: 84795582+clouddrove-ci@users.noreply.github.com
          git-commit-message: "readme: Update IAM's readme"
